#!/bin/sh
### BEGIN INIT INFO
# Provides:          nohang
# Required-Start:    $network $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Highly configurable out of memory preventer
### END INIT INFO


PATH=/sbin:/usr/local/sbin:/bin:/usr/bin
DESC=nohang
NAME=nohang
DAEMON=/usr/local/sbin/$NAME
PIDFILE=/run/$NAME.pid
LOGFILE=/var/log/$NAME.log
USER="root"





# Exit if the package is not installed
[ -x $DAEMON ] || exit 0








































