#!/usr/bin/env python3


# дополнительное из meminfo

from memco import *

while True:

    print("\033c")

    mc = mem_check_full()

    buffers = int(mc[3])
    cached = int(mc[4])
    active = int(mc[5])
    inactive = int(mc[6])
    shmem = int(mc[7])
    buffers_cached = buffers + cached
    used = active + inactive

    len2 = 8
    print('shared     {} G {} %'.format(human(shmem).rjust(len2, ' '), percent(shmem / mem_total)))
    print('buffers    {} G {} %'.format(human(buffers).rjust(len2, ' '), percent(buffers / mem_total)))
    print('cache      {} G {} %'.format(human(cached).rjust(len2, ' '), percent(cached / mem_total)))
    print('buff+cache {} G {} %'.format(human(buffers_cached).rjust(len2, ' '), percent(buffers_cached / mem_total)))
    print()
    print('active     {} G {} %'.format(human(active).rjust(len2, ' '), percent(active / mem_total)))
    print('inactive   {} G {} %'.format(human(inactive).rjust(len2, ' '), percent(inactive / mem_total)))

    sleep(0.1)


