#!/usr/bin/env python3

# загоняет в список файлы из dirpath

import os

dirpath = '/usr/share'

# размер среза
z = 160000

c = 5

def file_reader(path):
    try:
        with open(path, 'br') as file:
            return file.read()
    except FileNotFoundError:
        return None
    except OSError:
        return None



for i in range(c):
    print(i + 1, '/', c)
    path_list = []
    for d, dirs, files in os.walk(dirpath):
        for f in files:
            path = os.path.join(d, f)
            path_list.append(path)

    x = []
    for i in path_list[:z]:
        x.append(file_reader(i))
    del x
    del path_list



