#!/usr/bin/env python3

from sys import exit, argv
from argparse import ArgumentParser
import os
from time import sleep, monotonic


t0 = monotonic()





"""

./f02 -m 500 -f /usr/lib/chromium/chromium

-m
-f

os.path.isfile(path) 
os.path.isdir(path) 

"""

a = argv[1:]

la = len(a)

if la != 4:
    print('invalid input')
    exit(1)


parser = ArgumentParser()

parser.add_argument(
    '-f',
    help='path to file',
    default='',
    type=str
)

parser.add_argument(
    '-m',
    help='read MiB num',
    default=0,
    type=float
)

args = parser.parse_args()

mib_num = args.m

f_path = args.f



print(mib_num, f_path)



if os.path.isdir(f_path):
    is_file = True
elif os.path.isfile(f_path):
    is_file = False
else:
    print('invalid path')
    exit(1)


b_num = int(mib_num * 1024 * 1024)

m = 1


for _ in range(m):
    li = []
    cur_sum = 0

    while True:


        if cur_sum < b_num:
            #sleep(0.003)
            n = b_num - cur_sum


            with open(f_path, 'rb') as f:
                foo = f.read(n)
                fl = len(foo)
                cur_sum += fl
                li.append(foo)


            print(cur_sum)

        else:
            t1 = monotonic()
            t = t1 - t0
            print('OK, t:', round(t, 1))
            break
            #exit()

