#!/usr/bin/env python3




"""
- включать триггер и возвр его состиояние

- чек статус процесса на этипах: память и стейт, опц имя





"""













from time import sleep
from sys import stdout, stderr, argv, exit


pid = argv[1]


s = 0.05
k = 0.95


def rline1(path):
    """read 1st line from path."""
    with open(path) as f:
        for line in f:
            return line.rstrip()


def write(path, string):
    """
    """
    with open(path, 'w') as f:
        f.write(string)


def pid_to_rss(pid):
    """
    """
    rss = rline1('/proc/{}/statm'.format(pid)).split(' ')[1]
    return rss


def is_alive(pid):
    """
    """
    rss = pid_to_rss(pid)
    if rss == '0':
        return False
    else:
        return True


def trigger():
    """
    """
    write('/proc/sysrq-trigger', 'f')


def write_score(pid):
    """
    """
    write('/proc/{}/oom_score_adj'.format(pid), '1000')


print('PID:', pid)

print('Set oom_score_adj=1000')

write_score(pid)


while True:
    print('Trigger OOMK! Sleep', s)
    trigger()
    sleep(s)
    s = s * k
    try:
        x = is_alive(pid)
    except Exception as e:
        print(e)
        exit()
    if not x:
        print('VmRSS=0, exit')
        exit()
